name: imageopt
type: php
docroot: .test
php_version: "7.4"
composer_version: 2
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames:
    - v10.imageopt
    - v11.imageopt
additional_fqdns: []
provider: default
use_dns_when_possible: true
hooks:
    post-start:
        - exec: sudo sed -i '1s/^/TERM=xterm-256color\n/' ~/.bashrc
        - exec: mkdir -p .test && cp /var/www/html/.ddev/data-init/index.html /var/www/html/.test/

